# -*- coding: utf-8 -*-
# Part of external_id_manager. License: LGPL-3 <https://www.gnu.org/licenses/lgpl-3.0.html>.
import logging
import re
from collections import defaultdict

from odoo import _, api, fields, models, tools
from odoo.exceptions import AccessError, UserError

_logger = logging.getLogger(__name__)

# Modules the web importer/exporter uses for the external IDs it generates.
IMPORT_MODULES = ('__import__', '__export__')
# Searching by the *name of the target record* has to ask every model in turn
# (there is no join between ir_model_data and "whatever the record is"), so both
# the number of models visited and the hits kept per model are capped, and both
# caps are stated in the field help and on the store listing. The model cap is
# set above the number of models any real database registers, so it only exists
# to keep a pathological database from running the search forever.
NAME_SEARCH_MODEL_LIMIT = 1000
NAME_SEARCH_HIT_LIMIT = 200
# Physical table names come from the registry, never from user input; this
# pattern is a second belt so nothing but a plain identifier is ever inlined.
TABLE_NAME_RE = re.compile(r'^[a-z_][a-z0-9_$]*$')

# One row per ir.model.data row, same id, so an entry maps 1:1 onto the
# ir.model.data record it describes (that is what makes deleting a broken entry
# a plain ORM unlink on ir.model.data, with its access rights enforced).
ENTRY_VIEW_SQL = """
    SELECT d.id                                     AS id,
           d.module                                 AS module,
           d.name                                   AS name,
           CASE WHEN COALESCE(d.module, '') = ''
                THEN d.name
                ELSE d.module || '.' || d.name
           END                                      AS complete_name,
           d.model                                  AS model,
           m.id                                     AS model_id,
           d.res_id                                 AS res_id,
           COALESCE(d.noupdate, FALSE)              AS noupdate,
           d.create_date                            AS created_on,
           d.create_uid                             AS created_by,
           CASE WHEN d.module IN %(import_modules)s
                THEN 'import' ELSE 'data'
           END                                      AS source_type
      FROM ir_model_data d
      LEFT JOIN ir_model m ON m.model = d.model
"""


class ExternalIdEntry(models.Model):
    _name = 'external.id.entry'
    _description = 'External ID'
    _auto = False
    _rec_name = 'complete_name'
    _order = 'module, model, name'

    module = fields.Char(
        string='Module', readonly=True,
        help='Module (or import marker) that owns this external ID.',
    )
    name = fields.Char(
        string='Identifier', readonly=True,
        help='The part after the dot, unique within the module.',
    )
    complete_name = fields.Char(
        string='External ID', readonly=True,
        help='The full "module.identifier" string, as used in env.ref(), in '
             'data files and in the "External ID" column of a spreadsheet import.',
    )
    model = fields.Char(
        string='Model', readonly=True,
        help='Technical name of the model the referenced record belongs to.',
    )
    model_id = fields.Many2one(
        'ir.model', string='Model Name', readonly=True,
        help='The model as registered in the database. Empty when the model is '
             'no longer installed.',
    )
    res_id = fields.Integer(
        string='Record ID', readonly=True, group_operator=False,
        help='Database id of the referenced record.',
    )
    noupdate = fields.Boolean(
        string='Non Updatable', readonly=True,
        help='When ticked, module upgrades will not overwrite the referenced '
             'record with the values from the data file.',
    )
    source_type = fields.Selection(
        [('data', 'Module data file'), ('import', 'Import / Export')],
        string='Source', readonly=True,
        help='"Import / Export" covers the external IDs generated by the '
             'spreadsheet importer and exporter (modules __import__ and '
             '__export__). Everything else is declared by a module data file.',
    )
    created_on = fields.Datetime(
        string='Created On', readonly=True,
        help='When the external ID was created - for imports, when the '
             'spreadsheet was loaded.',
    )
    created_by = fields.Many2one(
        'res.users', string='Created By', readonly=True,
    )
    record_name = fields.Char(
        string='Record', compute='_compute_record_info', search='_search_record_name',
        help='Display name of the referenced record, resolved in bulk per '
             'model. Searching on it asks each model in turn - at most %s '
             'models, keeping at most %s matches in each - so it is slower '
             'than the other search fields and can miss matches beyond those '
             'caps.' % (NAME_SEARCH_MODEL_LIMIT, NAME_SEARCH_HIT_LIMIT),
    )
    record_status = fields.Selection(
        [
            ('ok', 'Record found'),
            ('broken', 'Broken - record missing'),
            ('unknown_model', 'Model not installed'),
        ],
        string='Status', compute='_compute_record_info', search='_search_record_status',
        help='"Broken" means the external ID still exists but the record it '
             'points to has been deleted, so env.ref() on it fails. "Model not '
             'installed" means the model itself is gone from this database, so '
             'the reference cannot be checked.',
    )
    is_broken = fields.Boolean(
        string='Broken Reference', compute='_compute_record_info', search='_search_is_broken',
        help='Ticked when the referenced record no longer exists.',
    )

    def init(self):
        # Read-only database view over ir_model_data. The only interpolated
        # value is self._table (derived from _name); %(import_modules)s is left
        # untouched by that interpolation and bound by psycopg2.
        tools.drop_view_if_exists(self.env.cr, self._table)
        self.env.cr.execute(
            'CREATE VIEW %s AS (%s)' % (self._table, ENTRY_VIEW_SQL),
            {'import_modules': IMPORT_MODULES},
        )

    # ------------------------------------------------------------------
    # Bulk resolution helpers - everything here works per model, never per row
    # ------------------------------------------------------------------
    @api.model
    def _model_table(self, model_name):
        """Physical table of ``model_name``, or None when it cannot be checked.

        None is returned for a model that is not in the registry any more (its
        module was uninstalled), for abstract models, and for a model whose
        table is missing from the database.
        """
        if not model_name or model_name not in self.env:
            return None
        model = self.env[model_name]
        if model._abstract:
            return None
        table = model._table
        if not table or not TABLE_NAME_RE.match(table):
            return None
        self.env.cr.execute(
            "SELECT 1 FROM pg_class WHERE relname = %s AND relkind IN ('r', 'v', 'm', 'p', 'f')",
            (table,),
        )
        return table if self.env.cr.fetchone() else None

    @api.model
    def _existing_res_ids(self, table, res_ids):
        """Ids of ``res_ids`` that still exist in ``table`` - one single query."""
        wanted = [res_id for res_id in res_ids if res_id]
        if not wanted:
            return set()
        # table is a registry table name validated against TABLE_NAME_RE above,
        # the ids are bound parameters: no user input reaches this statement.
        self.env.cr.execute(
            'SELECT id FROM "%s" WHERE id = ANY(%%s)' % table, (wanted,))
        return {row[0] for row in self.env.cr.fetchall()}

    @api.model
    def _display_names(self, model_name, res_ids):
        """{id: display name} for one model, read through the ORM in one go.

        Read as the current user, so record rules apply. The records are picked
        with search() rather than browse(): reading a record hidden by a record
        rule raises for the whole batch, which would blank the name of every
        other record of the same model, while search() simply leaves it out.
        A model the user may not read at all yields no name instead of breaking
        the list.
        """
        if not res_ids:
            return {}
        names = {}
        try:
            with self.env.cr.savepoint():
                model = self.env[model_name].with_context(
                    active_test=False, prefetch_fields=False,
                )
                for record in model.search([('id', 'in', sorted(res_ids))]):
                    names[record.id] = record.display_name
        except Exception:  # pylint: disable=broad-except
            # access error, or a model whose display name computation breaks on
            # records that are only half there: neither must kill the list
            _logger.debug('external_id_manager: cannot read names of %s', model_name, exc_info=True)
            return {}
        return names

    def _resolve(self):
        """{entry id: (status, record name)} read straight from the database.

        Grouped per model: one existence query and one name query per model.
        """
        result = {}
        per_model = defaultdict(list)
        for entry in self:
            # bucket on the model first, exactly like _status_ids does, so that
            # the badge on a line and the status filters can never disagree
            per_model[entry.model].append(entry)
        for model_name, entries in per_model.items():
            table = self._model_table(model_name)
            if table is None:
                for entry in entries:
                    result[entry.id] = ('unknown_model', False)
                continue
            existing = self._existing_res_ids(table, {e.res_id for e in entries})
            names = self._display_names(model_name, existing)
            for entry in entries:
                if entry.res_id and entry.res_id in existing:
                    result[entry.id] = ('ok', names.get(entry.res_id) or False)
                else:
                    # missing record, or no target at all: env.ref() fails on both
                    result[entry.id] = ('broken', False)
        return result

    @api.depends('model', 'res_id')
    def _compute_record_info(self):
        resolved = self._resolve()
        for entry in self:
            status, name = resolved.get(entry.id, ('broken', False))
            entry.record_status = status
            entry.is_broken = status == 'broken'
            entry.record_name = name

    @api.model
    def _status_ids(self):
        """({broken ids}, {ids whose model is not installed}) for the whole table.

        One query per distinct model, whatever the number of external IDs.
        """
        cr = self.env.cr
        # defensive: ir.model.data.model is NOT NULL in stock Odoo, but a row
        # without a model is as unverifiable as one of an uninstalled model,
        # and _resolve() classifies it that way too
        cr.execute("SELECT id FROM ir_model_data WHERE model IS NULL")
        broken, unknown = set(), {row[0] for row in cr.fetchall()}
        cr.execute("SELECT DISTINCT model FROM ir_model_data WHERE model IS NOT NULL")
        for (model_name,) in cr.fetchall():
            table = self._model_table(model_name)
            if table is None:
                cr.execute("SELECT id FROM ir_model_data WHERE model = %s", (model_name,))
                unknown.update(row[0] for row in cr.fetchall())
                continue
            # table validated against TABLE_NAME_RE, model name bound as a parameter
            cr.execute(
                'SELECT d.id FROM ir_model_data d '
                'LEFT JOIN "%s" t ON t.id = d.res_id '
                'WHERE d.model = %%s AND (d.res_id IS NULL OR d.res_id = 0 OR t.id IS NULL)' % table,
                (model_name,),
            )
            broken.update(row[0] for row in cr.fetchall())
        return broken, unknown

    # ------------------------------------------------------------------
    # Search methods for the computed columns
    # ------------------------------------------------------------------
    @api.model
    def _domain_values(self, value):
        """Right hand side of a domain leaf as a set.

        Odoo 18/19 rewrite "= x" into "in {x}" before calling a search method,
        and the container it passes is not always a plain list.
        """
        if isinstance(value, (str, bool, int)) or value is None:
            return {value}
        return set(value)

    def _search_is_broken(self, operator, value):
        if operator not in ('=', '!=', 'in', 'not in'):
            raise UserError(_('"Broken Reference" can only be searched with =, !=, in or not in.'))
        values = self._domain_values(value)
        if values - {True, False}:
            raise UserError(_('"Broken Reference" can only be searched for True or False.'))
        positive = operator in ('=', 'in')
        broken, _unknown = self._status_ids()
        # "not broken" is returned as the complement of the broken ids: broken
        # references are the rare case, so listing the healthy ones instead
        # would put the whole ir_model_data table inside the domain
        if values == {True}:
            return [('id', 'in' if positive else 'not in', sorted(broken))]
        if values == {False}:
            return [('id', 'not in' if positive else 'in', sorted(broken))]
        # asked for both values (matches everything) or for none (matches nothing)
        matches_all = bool(values) if positive else not values
        return [('id', 'not in' if matches_all else 'in', [])]

    def _search_record_status(self, operator, value):
        if operator not in ('=', '!=', 'in', 'not in'):
            raise UserError(_('"Status" can only be searched with =, !=, in or not in.'))
        values = self._domain_values(value)
        unsupported = values - {'ok', 'broken', 'unknown_model'}
        if unsupported:
            raise UserError(_('Unknown external ID status: %s',
                              ', '.join(sorted(map(str, unsupported)))))
        positive = operator in ('=', 'in')
        broken, unknown = self._status_ids()
        if 'ok' in values:
            # same reason as above: exclude the unhealthy ids instead of
            # enumerating every healthy one
            excluded = set()
            if 'broken' not in values:
                excluded |= broken
            if 'unknown_model' not in values:
                excluded |= unknown
            return [('id', 'not in' if positive else 'in', sorted(excluded))]
        selected = set()
        if 'broken' in values:
            selected |= broken
        if 'unknown_model' in values:
            selected |= unknown
        return [('id', 'in' if positive else 'not in', sorted(selected))]

    def _search_record_name(self, operator, value):
        positive_op = {
            '=': '=', 'like': 'like', 'ilike': 'ilike', '=like': '=like', '=ilike': '=ilike',
            '!=': '=', 'not like': 'like', 'not ilike': 'ilike',
        }.get(operator)
        if not positive_op or not isinstance(value, str):
            raise UserError(_(
                'The referenced record name can only be searched with a text '
                'operator (=, !=, like, ilike).'))
        cr = self.env.cr
        cr.execute("SELECT DISTINCT model FROM ir_model_data WHERE model IS NOT NULL ORDER BY model")
        matched = set()
        visited = 0
        for (model_name,) in cr.fetchall():
            if visited >= NAME_SEARCH_MODEL_LIMIT:
                break
            if self._model_table(model_name) is None:
                continue
            model = self.env[model_name]
            if not (getattr(model, '_rec_names_search', None) or model._rec_name):
                # a model with nothing to search a name on answers "everything
                # matches"; that would fill the result with false positives
                continue
            visited += 1
            try:
                # a model the user may not read, or one with a name search that
                # raises, must not break the search: skip it
                with cr.savepoint():
                    pairs = self.env[model_name].with_context(active_test=False).name_search(
                        name=value, operator=positive_op, limit=NAME_SEARCH_HIT_LIMIT)
            except Exception:  # pylint: disable=broad-except
                _logger.debug('external_id_manager: name search skipped %s', model_name, exc_info=True)
                continue
            hit_ids = [pair[0] for pair in pairs]
            if hit_ids:
                cr.execute(
                    "SELECT id FROM ir_model_data WHERE model = %s AND res_id = ANY(%s)",
                    (model_name, hit_ids),
                )
                matched.update(row[0] for row in cr.fetchall())
        positive = operator in ('=', 'like', 'ilike', '=like', '=ilike')
        return [('id', 'in' if positive else 'not in', sorted(matched))]

    # ------------------------------------------------------------------
    # Actions
    # ------------------------------------------------------------------
    def action_open_record(self):
        """Open the record this external ID points to."""
        self.ensure_one()
        status, _name = self._resolve().get(self.id, ('broken', False))
        if status == 'unknown_model':
            raise UserError(_(
                'The model "%s" is not installed in this database, so the '
                'record cannot be opened.', self.model))
        if status != 'ok':
            raise UserError(_(
                'This external ID is broken: %(xmlid)s points to %(model)s '
                'record %(res_id)s, which no longer exists.',
                xmlid=self.complete_name, model=self.model, res_id=self.res_id))
        return self.env[self.model].browse(self.res_id).get_formview_action()

    def action_delete_broken(self):
        """Delete the ir.model.data rows behind BROKEN entries only.

        Live external IDs are never deleted here: removing one makes the next
        upgrade of its module create a duplicate record instead of updating the
        existing one.
        """
        if not self.env.user.has_group('base.group_system'):
            raise AccessError(_('Only Settings administrators may delete external IDs.'))
        resolved = self._resolve()
        kept = self.filtered(lambda entry: resolved.get(entry.id, ('broken', False))[0] != 'broken')
        if kept:
            raise UserError(_(
                'Only broken external IDs can be deleted here.\n\n'
                'These still point to an existing record (or to a model that is '
                'not installed, so nothing can be checked):\n%s\n\n'
                'Deleting a live external ID silently breaks module upgrades: '
                'the upgrade no longer finds the record and creates a duplicate '
                'instead of updating it.',
                '\n'.join('- %s' % entry.complete_name for entry in kept[:20])))
        # ir.model.data unlink is access-checked as the current user (Settings
        # administrators inherit it from Access Rights); it also clears the
        # external ID caches.
        self.env['ir.model.data'].browse(self.ids).unlink()
        return self.env['ir.actions.act_window']._for_xml_id(
            'external_id_manager.action_external_id_entry')
